const data = {
    products: [
        {
            _id: '1',
            name: 'Scanfrost 4 Gas Burner SFC5402B',
            category: 'Gas 0 50 50*55 Black Finished',
            images: '/images/cok2.jpg',
            price: '95', 
            countInStock: 10,
            brand: '4 GAS Burner',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'QASA Washing Machine- Wash and Spin',
            category: 'Wash and Spin',
            images: '/images/mach.jpg',
            price: '100',
            countInStock: 20,
            brand: 'QASA',
            rating:4.0,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Nike Slime Shirt',
            category: 'Shirt',
            images: '/images/cok2.jpg',
            price: '50',
            countInStock: 0,
            brand: 'Nike',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Corolla 3.5kva Max Manual Generator',
            category: 'Shirt',
            images: '/images/Ger5s.jpg',
            price: '90',
            countInStock: 15,
            brand: 'Generator',
            rating:4.5,
            numReviews:10,
            description: 'Low Noise Technology high quality product',
        },
        {
            _id: '5',
            name: 'Nike Slime Shirt',
            category: 'Shirt',
            images: '/images/tv2.jpg',
            price: '20',
            countInStock: 5,
            brand: 'Nike',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Maxi Gas Cooker-maxi60',
            category: 'Gas Cooker',
            images: '/images/cok1.jpg',
            price: '17',
            countInStock: 12,
            brand: 'Maxi',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '7',
            name: 'Polystar 4.5kg Top Loader Single Tub ',
            category: 'Wsahing Machine',
            images: '/images/mech1.jpg',
            price: '60',
            countInStock: 3,
            brand: 'Polystar Wsahing Machine',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '8',
            name: 'Devon Vegetable Oil- 5L',
            category: 'Shirt',
            images: '/images/oil4.jpg',
            price: '15',
            countInStock: 25,
            brand: 'Devon',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '9',
            name: 'iTEC Electric Start, 3.5kva Power',
            category: 'Generator',
            images: '/images/Ger3.jpg',
            price: '150',
            countInStock: 25,
            brand: 'iTEC',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '10',
            name: 'Grand Vegetable Oil- 25L',
            category: 'Vegetable Oil',
            images: '/images/oil2.jpg',
            price: '40',
            countInStock: 25,
            brand: 'Grand',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '11',
            name: 'Hennessy Vs Cognac -70cl -Single Bottle',
            category: 'Shirt',
            images: '/images/wine1.jpg',
            price: '50',
            countInStock: 25,
            brand: 'Hennessy',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '12',
            name: 'Tiger Balm 0-9kv Generator',
            category: 'TG1500',
            images: '/images/Ger7.jpg',
            price: '50',
            countInStock: 25,
            brand: 'Tiger Balm',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        
    ],
};

export default data;