const data = {
    products: [
        {
            _id: '1',
            name: 'Mida 4-burner Gas Cooker with Oven',
            category: 'Gas 0 50 50*55 Black Finished',
            images: '/images/cooking1.jpg',
            price: '95', 
            countInStock: 10,
            brand: '4 GAS Burner',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Scanfrost 4 Gas Burner SFC5402B',
            category: 'Gas 0 50 50*55 Black Finished',
            images: '/images/cok2.jpg',
            price: '100',
            countInStock: 20,
            brand: 'SCANFROST',
            rating:4.0,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Maxi Gas Cooker-maxi60*90',
            category: '4 GAS Burner',
            images: '/images/cok1.jpg',
            price: '50',
            countInStock: 0,
            brand: 'MAXI',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Maxi Gas Cooker-maxi60*90 ',
            category: '4 GAS Burner',
            images: '/images/cok1.jpg',
            price: '90',
            countInStock: 15,
            brand: 'MAXI',
            rating:4.5,
            numReviews:10,
            description: 'Low Noise Technology high quality product',
        },
        {
            _id: '5',
            name: 'SAMSUNG 42" Class 4k Crystal UHD',
            category: 'LED Smart TV',
            images: '/images/tv2.jpg',
            price: '20',
            countInStock: 5,
            brand: 'SAMSUNG',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Gasoline Generator CL-1500B',
            category: 'Jinlong Myanmar',
            images: '/images/Ger3.jpg',
            price: '40',
            countInStock: 12,
            brand: 'Gasoline GENERATOR',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '7',
            name: 'Akai Washing Machine+ spinning-4kg ',
            category: 'Wsahing Machine',
            images: '/images/wash.jpg',
            price: '60',
            countInStock: 3,
            brand: 'AKAI Wsahing Machine',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '8',
            name: 'Grand Vegetable Oil- 10L',
            category: 'Grand veg',
            images: '/images/oil2.jpg',
            price: '25',
            countInStock: 25,
            brand: 'Grand',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '9',
            name: 'LG Home Theater System Bluetooth',
            category: 'Dvd-Lhd667-600w',
            images: '/images/Home.jpg',
            price: '150',
            countInStock: 25,
            brand: 'LG',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '10',
            name: 'ITEC 45" ULD Smart Android',
            category: 'Television',
            images: '/images/tv5.jpg',
            price: '40',
            countInStock: 25,
            brand: 'ITEC',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '11',
            name: 'Ultimate over-ear Headphones',
            category: 'Beoplay H95',
            images: '/images/Headphone1.jpg',
            price: '50',
            countInStock: 25,
            brand: 'HEADPHONE',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '12',
            name: '55 Inch Curved 4k UHD Smart Tv',
            category: 'UHD TV',
            images: '/images/tv10.jpg',
            price: '50',
            countInStock: 25,
            brand: 'SNMSUNG',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '13',
            name: 'QASA Twin Tub Washing Machine',
            category: 'Washing Machine',
            images: '/images/mach.jpg',
            price: '50',
            countInStock: 25,
            brand: 'QASA',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '14',
            name: 'Iphone 12 pro- 6.8" ROM- 64GB RAM',
            category: 'Iphone',
            images: '/images/Iphone1.jpg',
            price: '3000',
            countInStock: 25,
            brand: 'IPHONE',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '15',
            name: 'Dell Latitude 7400-intel Core 17 ',
            category: 'Core 17',
            images: '/images/Hp1.jpg',
            price: '50',
            countInStock: 25,
            brand: 'DELL',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '16',
            name: 'Scanfrost 4 Gas Burner SFC5402B',
            category: '4 Gas Burner',
            images: '/images/cok2.jpg',
            price: '50',
            countInStock: 25,
            brand: 'SCANFROST',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '17',
            name: 'CD Player and in ear head',
            category: 'SONG',
            images: '/images/mediaplayer.jpg',
            price: '50',
            countInStock: 25,
            brand: 'SONG CD Player',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '18',
            name: 'Orlando Baracelet Wrist watch',
            category: 'MEN- GOLD',
            images: '/images/watchwr.jpg',
            price: '50',
            countInStock: 25,
            brand: 'ORLANDO',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '19',
            name: 'Next-gen wireless earbuds',
            category: 'Headphones',
            images: '/images/earp1.jpg',
            price: '50',
            countInStock: 25,
            brand: 'EARBUDS',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id: '20',
            name: 'Apple Macbook PRO 15.4"',
            product: '16GB ROM-256 RAM',
            category: 'Macbook',
            images: '/images/IPAD1.jpg',
            price: '50',
            countInStock: 25,
            brand: 'APPLE MACBOOK',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
    ],
};

export default data;